import { HEX_TOKEN, ID, ID_LIST, SHARE_TOKEN, SLUG, type ArgTemplate } from "@/__tests__/helpers/action-id-sweep";

/**
 * Every export of every "use server" module under lib/actions, keyed
 * "<module>#<export>". Each entry is an argument template for one call: the
 * markers (ID, ID_LIST, SLUG, HEX_TOKEN, SHARE_TOKEN) are the identifier
 * positions the sweep test fills with malformed values, one position at a
 * time, while every other marker gets a well-formed value. Non-identifier
 * fields are left out: a schema that rejects the call for a missing field
 * still has to do so without passing a malformed id along.
 *
 * A new server action must be added here (or to NO_ID_ARGUMENTS) or the
 * guard test fails.
 */
export const ACTION_ID_ARGUMENTS: Record<string, ArgTemplate> = {
  "account-lifecycle#confirmEmailChange": [SHARE_TOKEN],
  "account-lifecycle#confirmEmailVerification": [SHARE_TOKEN],
  "account-lifecycle#resetPassword": [{ token: SHARE_TOKEN }],
  "admin#approveUser": [ID],
  "admin#rejectUser": [ID],
  "association-profile#getPublicAssociationProfile": [SLUG],
  "association-profile#getPublicAssociationTeams": [ID],
  "association-profile#getPublicTeamProfile": [ID, SLUG],
  "association-profile#resolveActiveAssociation": [SLUG],
  "association-profile#resolvePublicAssociation": [SLUG],
  "association-profile#resolvePublicTeam": [ID, SLUG],
  "association-profile#setAssociationProfilePublished": [{ leagueId: ID }],
  "association-profile#updateAssociationProfile": [{ leagueId: ID }],
  "association-profile#updateAssociationSlug": [{ leagueId: ID, slug: SLUG }],
  "association-profile#updateTeamPublicProfile": [{ leagueId: ID, teamId: ID, slug: SLUG }],
  "association-roles#grantAssociationResponsibility": [{ leagueId: ID, userId: ID, divisionId: ID, teamId: ID, seasonId: ID, eventId: ID, signupEventId: ID }],
  "association-roles#inviteAssociationOperator": [{ leagueId: ID, teamId: ID, divisionId: ID, seasonId: ID, eventId: ID, signupEventId: ID }],
  "association-roles#listAssociationResponsibilityGrants": [ID],
  "association-roles#revokeAssociationResponsibility": [{ grantId: ID, leagueId: ID }],
  "audit#getAuditActionsForLeague": [ID],
  "audit#getAuditLogsAction": [{ leagueId: ID }],
  "auth#signup": [{ invitationToken: HEX_TOKEN }],
  "branding#clearEntityLogo": [{ entityId: ID }],
  "branding#setEntityBrandColors": [{ entityId: ID }],
  "branding#setEntityLogo": [{ entityId: ID }],
  "communication#getLeagueMessages": [{ leagueId: ID }],
  "communication#getTeamMessages": [{ teamId: ID }],
  "communication#sendLeagueMessage": [{ leagueId: ID, targeting: { divisionIds: ID_LIST, teamIds: ID_LIST } }],
  "communication#sendTeamMessage": [{ teamId: ID }],
  "event-invitations#listEventInvitations": [ID],
  "event-invitations#resendEventInvitation": [{ invitationId: ID }],
  "event-invitations#revokeEventInvitation": [{ invitationId: ID }],
  "event-invitations#sendEventInvitations": [{ eventId: ID }],
  "event-managers#addEventManager": [{ eventId: ID }],
  "event-managers#listEventManagers": [ID],
  "event-managers#removeEventManager": [{ managerId: ID }],
  "event-media#finalizeEventMediaUpload": [{ eventId: ID }],
  "event-media#listEventMedia": [{ eventId: ID, linkToken: HEX_TOKEN }],
  "event-media#removeEventMediaItem": [{ mediaItemId: ID }],
  "event-media#reportEventMediaItem": [{ mediaItemId: ID }],
  "event-registrations#cancelMyEventRegistration": [{ registrationId: ID }],
  "event-registrations#claimWaitlistOffer": [{ registrationId: ID }],
  "event-registrations#declineWaitlistOffer": [{ registrationId: ID }],
  "event-registrations#getEventRoster": [{ eventId: ID }],
  "event-registrations#promoteWaitlistEntry": [{ registrationId: ID }],
  "event-registrations#refundEventRegistration": [{ registrationId: ID }],
  "event-registrations#registerForSignupEvent": [{ eventId: ID, slotId: ID, linkToken: HEX_TOKEN }],
  "event-registrations#removeEventRegistration": [{ registrationId: ID }],
  "event-registrations#setEventCheckIn": [{ registrationId: ID }],
  "event-registrations#setManualPaymentStatus": [{ registrationId: ID }],
  "event-teams#assignToEventTeam": [{ eventTeamId: ID, registrationIds: ID_LIST }],
  "event-teams#deleteEventGame": [{ gameId: ID }],
  "event-teams#deleteEventTeam": [{ teamId: ID }],
  "event-teams#getEventStandings": [ID, HEX_TOKEN],
  "event-teams#getEventTeamsBoard": [ID],
  "event-teams#getMyEventAssignments": [ID],
  "event-teams#getPublicEventGames": [ID, HEX_TOKEN],
  "event-teams#listPublicVenueEventGames": [ID],
  "event-teams#publishEventTeams": [{ eventId: ID }],
  "event-teams#recordGameResult": [{ gameId: ID }],
  "event-teams#removeTeamAssignment": [{ registrationId: ID }],
  "event-teams#setFloater": [{ registrationId: ID }],
  "event-teams#setGameRotation": [{ gameId: ID }],
  "event-teams#upsertEventGame": [{ eventId: ID, homeTeamId: ID, awayTeamId: ID, gameId: ID, surfaceId: ID, segmentId: ID, reservationId: ID, venueId: ID }],
  "event-teams#upsertEventTeam": [{ eventId: ID, teamId: ID }],
  "events#createEvent": [{ teamId: ID, venueId: ID, reservationId: ID }],
  "events#createInterTeamGame": [{ leagueId: ID, homeTeamId: ID, awayTeamId: ID }],
  "events#deleteEvent": [ID],
  "events#getEvent": [ID],
  "events#getTeamEvents": [ID],
  "events#updateEvent": [{ teamId: ID, id: ID, venueId: ID, reservationId: ID }],
  "game-proposals#acceptGameProposal": [{ proposalId: ID, reservationId: ID }],
  "game-proposals#counterGameProposal": [{ proposalId: ID, venueId: ID }],
  "game-proposals#createGameProposal": [{ proposingTeamId: ID, receivingTeamId: ID, seasonId: ID, venueId: ID }],
  "game-proposals#declineGameProposal": [{ proposalId: ID }],
  "game-proposals#getProposalsForLeague": [ID],
  "game-proposals#getProposalsForTeam": [ID],
  "game-proposals#withdrawGameProposal": [{ proposalId: ID }],
  "gear-context#getGearInventoryContext": [ID],
  "gear-context#getGearReservationContext": [ID],
  "gear-inventory#adjustGearPoolStock": [{ leagueId: ID, catalogItemId: ID, locationId: ID }],
  "gear-inventory#archiveGearCatalogItem": [{ leagueId: ID, catalogItemId: ID }],
  "gear-inventory#archiveGearStorageLocation": [{ leagueId: ID, locationId: ID }],
  "gear-inventory#changeGearUnitCondition": [{ leagueId: ID, unitId: ID }],
  "gear-inventory#createGearCatalogItem": [{ leagueId: ID }],
  "gear-inventory#createGearStorageLocation": [{ leagueId: ID }],
  "gear-inventory#createGearUnit": [{ leagueId: ID, catalogItemId: ID, currentLocationId: ID }],
  "gear-inventory#retireGearUnit": [{ leagueId: ID, unitId: ID }],
  "gear-inventory#transferGearPoolStock": [{ leagueId: ID, catalogItemId: ID, sourceLocationId: ID, destinationLocationId: ID }],
  "gear-inventory#transferGearUnit": [{ leagueId: ID, unitId: ID, destinationLocationId: ID }],
  "gear-inventory#unretireGearUnit": [{ leagueId: ID, unitId: ID, destinationLocationId: ID }],
  "gear-inventory#updateGearCatalogItem": [{ leagueId: ID, catalogItemId: ID }],
  "gear-inventory#updateGearStorageLocation": [{ leagueId: ID, locationId: ID }],
  "gear-inventory#updateGearUnit": [{ leagueId: ID, unitId: ID }],
  "gear-needs#approveTeamGearNeed": [{ leagueId: ID, needId: ID }],
  "gear-needs#cancelTeamGearNeed": [{ leagueId: ID, needId: ID }],
  "gear-needs#createTeamGearNeed": [{ leagueId: ID, teamId: ID }],
  "gear-needs#decideTeamGearNeed": [{ leagueId: ID, needId: ID }],
  "gear-needs#fulfillTeamGearNeed": [{ leagueId: ID, needId: ID }],
  "gear-needs#getGearNeedDetail": [ID, ID],
  "gear-needs#getGearNeedsContext": [ID],
  "gear-needs#getTeamGearNeeds": [ID, ID],
  "gear-needs#submitTeamGearNeed": [{ leagueId: ID, needId: ID }],
  "gear-pledges#cancelGearPledge": [{ leagueId: ID, pledgeId: ID }],
  "gear-pledges#correctGearPledgeReceipt": [{ leagueId: ID, pledgeId: ID, receiptId: ID }],
  "gear-pledges#createGearPledge": [{ wishlistToken: SHARE_TOKEN, wishlistItemId: ID }],
  "gear-pledges#createPublicGearPledge": [{ wishlistToken: SHARE_TOKEN, wishlistItemId: ID }],
  "gear-pledges#declineGearPledge": [{ leagueId: ID, pledgeId: ID }],
  "gear-pledges#expireGearPledge": [{ leagueId: ID, pledgeId: ID }],
  "gear-pledges#getGearPledgeAdminContext": [ID],
  "gear-pledges#getGearPledgesForAdmin": [ID],
  "gear-pledges#receiveGearPledge": [{ leagueId: ID, pledgeId: ID, catalogItemId: ID, poolStockId: ID, gearUnitId: ID, locationId: ID }],
  "gear-pledges#redactGearPledgePii": [{ leagueId: ID, pledgeId: ID }],
  "gear-pledges#updateGearPledgeStatus": [{ leagueId: ID, pledgeId: ID }],
  "gear-reservations#approveAndAllocateGearReservation": [{ leagueId: ID, reservationId: ID }],
  "gear-reservations#cancelGearReservation": [{ leagueId: ID, reservationId: ID }],
  "gear-reservations#createGearReservation": [{ leagueId: ID, teamId: ID }],
  "gear-reservations#declineGearReservation": [{ leagueId: ID, reservationId: ID }],
  "gear-reservations#getGearReservationAllocationOptions": [{ leagueId: ID, reservationId: ID, reservationLineId: ID }],
  "gear-reservations#recordGearPickup": [{ leagueId: ID, allocationId: ID }],
  "gear-reservations#recordGearReturn": [{ leagueId: ID, allocationId: ID }],
  "gear-reservations#releaseGearAllocation": [{ leagueId: ID, allocationId: ID }],
  "gear-reservations#rescheduleGearReservation": [{ leagueId: ID, reservationId: ID }],
  "gear-wishlist#archiveGearWishlist": [{ leagueId: ID }],
  "gear-wishlist#getGearWishlistAdminContext": [ID],
  "gear-wishlist#getGearWishlistForAdmin": [ID],
  "gear-wishlist#getPublicGearWishlist": [SHARE_TOKEN],
  "gear-wishlist#rotateGearWishlistShareToken": [{ leagueId: ID }],
  "gear-wishlist#saveGearWishlist": [{ leagueId: ID }],
  "gear-wishlist#setGearWishlistStatus": [{ leagueId: ID }],
  "guardians#addGuardian": [{ playerId: ID }],
  "guardians#listGuardians": [ID],
  "guardians#removeGuardian": [{ guardianId: ID }],
  "invitations#resendInvitation": [ID],
  "invitations#sendInvitation": [{ teamId: ID }],
  "invitations#sendLeagueInvitation": [{ teamId: ID, leagueId: ID }],
  "invitations#sendLeagueMemberInvitation": [{ leagueId: ID }],
  "league#addTeamToLeague": [{ leagueId: ID, divisionId: ID }],
  "league#assignTeamToDivision": [{ teamId: ID, divisionId: ID, leagueId: ID }],
  "league#createDivision": [{ leagueId: ID }],
  "league#deleteDivision": [{ id: ID, leagueId: ID }],
  "league#exportAttendanceReportCSV": [ID],
  "league#exportAttendanceReportPDF": [ID],
  "league#exportFinancialReportCSV": [ID],
  "league#exportFinancialReportPDF": [ID],
  "league#exportLeagueRosterCSV": [ID],
  "league#exportLeagueRosterPDF": [ID],
  "league#exportLeagueScheduleCSV": [ID],
  "league#exportLeagueSchedulePDF": [ID],
  "league#getLeagueDivisions": [ID],
  "league#getLeagueStatisticsData": [ID],
  "league#getLeagueTeamsPaginated": [{ leagueId: ID, divisionId: ID }],
  "league#getLeagueTeamsWithDivisions": [ID],
  "league#getLeagueWithStats": [ID],
  "league#migrateTeamToLeague": [{ teamId: ID }],
  "league#updateDivision": [{ id: ID, leagueId: ID }],
  "league#updateLeagueSettings": [{ id: ID }],
  "league-context#getLeagueInvitationsData": [ID],
  "league-context#getLeagueMessagesData": [ID],
  "league-context#getLeagueRosterData": [ID],
  "league-context#getLeagueScheduleData": [ID],
  "league-context#getNewLeagueGameContext": [ID],
  "league-payments#getLeaguePaymentsOverview": [ID],
  "league-payments#getLeagueStripeDashboardLink": [{ leagueId: ID }],
  "league-payments#refreshLeagueStripeStatus": [{ leagueId: ID }],
  "league-payments#startLeagueStripeOnboarding": [{ leagueId: ID }],
  "notifications#generateUnsubscribeToken": [ID],
  "notifications#getNotificationPreferences": [ID],
  "notifications#handleUnsubscribe": [{ token: HEX_TOKEN }],
  "notifications#updateNotificationPreferences": [{ leagueId: ID }],
  "permissions#assignLeagueRoleAction": [{ leagueId: ID, targetUserId: ID }],
  "permissions#assignTeamRoleAction": [{ leagueId: ID, teamId: ID, targetUserId: ID }],
  "permissions#checkPermissionAction": [ID, undefined, ID],
  "permissions#getLeagueUsersAction": [{ leagueId: ID }],
  "permissions#getTeamMembersWithRoles": [ID, ID],
  "permissions#getUserPermissionsAction": [{ leagueId: ID, targetUserId: ID }],
  "permissions#removeLeagueRoleAction": [{ leagueId: ID, targetUserId: ID }],
  "permissions#removeTeamRoleAction": [{ leagueId: ID, teamId: ID, targetUserId: ID }],
  "placements#createDivisionInline": [{ leagueId: ID }],
  "placements#getPlacementBoard": [{ seasonId: ID, phaseId: ID }],
  "placements#recordPlacement": [{ seasonId: ID, teamId: ID, divisionId: ID }],
  "plays#createPlay": [{ teamId: ID }],
  "plays#deletePlay": [{ id: ID, teamId: ID }],
  "plays#getPlayById": [{ id: ID, teamId: ID }],
  "plays#getPlaysByTeam": [{ teamId: ID }],
  "plays#updatePlay": [{ id: ID, teamId: ID }],
  "practice-plan-import#importPracticePlan": [{ teamId: ID }],
  "practice-session-drills#copySessionDrillToLibrary": [{ playId: ID, teamId: ID }],
  "practice-session-drills#duplicatePracticeSession": [{ id: ID, teamId: ID }],
  "practice-session-drills#saveSessionDrill": [{ sessionId: ID, teamId: ID, playId: ID }],
  "practice-session-queries#getPracticeSessionDetail": [ID],
  "practice-session-queries#getPracticeSessionForEdit": [ID],
  "practice-session-queries#getPracticeStaffOptions": [ID],
  "practice-sessions#createPracticeSession": [{ teamId: ID, venueId: ID, surfaceId: ID, segmentId: ID, reservationId: ID }],
  "practice-sessions#deletePracticeSession": [{ id: ID, teamId: ID }],
  "practice-sessions#getPracticeSessionById": [{ id: ID, teamId: ID }],
  "practice-sessions#getPracticeSessionsByTeam": [{ teamId: ID }],
  "practice-sessions#sharePracticeSession": [{ id: ID, teamId: ID }],
  "practice-sessions#updatePracticeSession": [{ id: ID, teamId: ID, venueId: ID, surfaceId: ID, segmentId: ID, reservationId: ID }],
  "public-content#archivePublicContent": [ID],
  "public-content#createPublicContent": [{ leagueId: ID, slug: SLUG, teamId: ID }],
  "public-content#getPublicContentItem": [SLUG, SLUG],
  "public-content#listAssociationContent": [ID],
  "public-content#listPublicAssociationContent": [ID],
  "public-content#listPublicAssociationContentPage": [ID],
  "public-content#updatePublicContent": [{ itemId: ID }],
  "roster#addPlayer": [{ teamId: ID }],
  "roster#deletePlayer": [ID, ID],
  "roster#exportLeagueRoster": [ID],
  "roster#transferPlayer": [{ playerId: ID, fromTeamId: ID, toTeamId: ID, leagueId: ID }],
  "roster#updatePlayer": [{ teamId: ID, id: ID }],
  "roster#updateTeamMemberUsahId": [{ teamMemberId: ID, teamId: ID }],
  "rsvp#getEventAttendance": [ID],
  "rsvp#submitRSVP": [{ eventId: ID, playerId: ID }],
  "rsvp#updateRSVP": [{ eventId: ID, playerId: ID }],
  "season-games#cancelSeasonGame": [{ gameId: ID }],
  "season-games#checkGameConflicts": [{ venueId: ID, surfaceId: ID, excludeGameId: ID }],
  "season-games#createSeasonGame": [{ homeTeamId: ID, awayTeamId: ID, seasonId: ID, phaseId: ID, venueId: ID, surfaceId: ID, segmentId: ID, reservationId: ID }],
  "season-games#deleteDraftGame": [{ gameId: ID }],
  "season-games#publishSeasonGames": [{ seasonId: ID, gameIds: ID_LIST }],
  "season-games#recordSeasonGameScore": [{ gameId: ID }],
  "season-games#updateSeasonGame": [{ gameId: ID, phaseId: ID, venueId: ID, surfaceId: ID, segmentId: ID, reservationId: ID }],
  "season-generation#generateRoundRobin": [{ seasonId: ID, teamIds: ID_LIST, phaseId: ID, defaultVenueId: ID }],
  "season-generation#previewRoundRobin": [{ seasonId: ID, teamIds: ID_LIST, phaseId: ID, defaultVenueId: ID }],
  "seasons#archiveSeason": [{ seasonId: ID }],
  "seasons#createSeason": [{ leagueId: ID, teamId: ID }],
  "seasons#createSeasonPhase": [{ seasonId: ID }],
  "seasons#deleteSeasonPhase": [{ phaseId: ID }],
  "seasons#getSeasonDetail": [ID],
  "seasons#getSeasons": [{ leagueId: ID, teamId: ID }],
  "seasons#unarchiveSeason": [{ seasonId: ID }],
  "seasons#updateSeason": [{ seasonId: ID }],
  "seasons#updateSeasonPhase": [{ phaseId: ID }],
  "session-registrations#cancelMyRegistration": [{ registrationId: ID }],
  "session-registrations#getVenueRegistrations": [{ organizationId: ID, venueId: ID }],
  "session-registrations#refundRegistration": [{ organizationId: ID, venueId: ID, registrationId: ID }],
  "session-registrations#registerForSession": [{ venueId: ID, scheduleBlockId: ID, lessonOfferingId: ID }],
  "signup-events#cancelSignupEvent": [{ eventId: ID }],
  "signup-events#createSignupEvent": [{ venueId: ID, hostOrganizationId: ID, hostLeagueId: ID, hostTeamId: ID }],
  "signup-events#duplicateSignupEvent": [{ eventId: ID }],
  "signup-events#getManagedSignupEvent": [ID],
  "signup-events#getPublicSignupEvent": [{ eventId: ID, linkToken: HEX_TOKEN }],
  "signup-events#listHostGroupOptions": [{ kind: "league", id: ID, eventId: ID }],
  "signup-events#listPublicSignupEvents": [{ venueId: ID, hostLeagueId: ID, hostOrganizationId: ID }],
  "signup-events#publishSignupEvent": [{ eventId: ID }],
  "signup-events#regenerateEventLink": [{ eventId: ID }],
  "signup-events#updateSignupEvent": [{ eventId: ID, venueId: ID }],
  "team#updateTeam": [{ id: ID }],
  "team-context#getTeamOverviewData": [ID],
  "team-context#getTeamRosterDataById": [ID],
  "team-officials#createTeamOfficial": [{ teamId: ID }],
  "team-officials#getTeamOfficials": [ID],
  "team-officials#inviteTeamOfficial": [{ teamId: ID }],
  "team-officials#removeTeamOfficial": [{ teamId: ID, officialId: ID }],
  "team-officials#updateTeamOfficial": [{ teamId: ID, officialId: ID }],
  "venue-content#archiveLessonOffering": [{ organizationId: ID, venueId: ID, lessonOfferingId: ID }],
  "venue-content#archiveVenueContentPost": [{ organizationId: ID, venueId: ID, postId: ID }],
  "venue-content#assignSkillLevelsToLesson": [{ organizationId: ID, venueId: ID, skillLevelIds: ID_LIST, lessonOfferingId: ID, scheduleBlockId: ID }],
  "venue-content#assignSkillLevelsToScheduleBlock": [{ organizationId: ID, venueId: ID, skillLevelIds: ID_LIST, scheduleBlockId: ID, lessonOfferingId: ID }],
  "venue-content#createLessonOffering": [{ organizationId: ID, venueId: ID, surfaceId: ID }],
  "venue-content#createSkillLevelReference": [{ organizationId: ID, venueId: ID }],
  "venue-content#getPublicVenueContent": [ID, { skillLevelIds: ID_LIST }],
  "venue-content#getVenueContentAdminData": [ID, ID],
  "venue-content#publishLessonOffering": [{ organizationId: ID, venueId: ID, lessonOfferingId: ID }],
  "venue-content#publishSpecialtyEvent": [{ organizationId: ID, venueId: ID, surfaceId: ID, segmentId: ID }],
  "venue-content#saveVenueContentPost": [{ organizationId: ID, venueId: ID, slug: SLUG, postId: ID }],
  "venue-layout#clearVenueLayout": [ID],
  "venue-layout#getVenueLayout": [ID],
  "venue-layout#saveVenueLayout": [{ venueId: ID }],
  "venue-organizations#attachVenueToOrganization": [{ organizationId: ID, venueId: ID }],
  "venue-organizations#createOrganizationVenue": [{ teamId: ID, leagueId: ID, organizationId: ID }],
  "venue-organizations#getPublicRinkProfile": [SLUG],
  "venue-organizations#publishVenueProfile": [{ organizationId: ID, venueId: ID }],
  "venue-organizations#updateVenueProfile": [{ organizationId: ID, venueId: ID, slug: SLUG }],
  "venue-payments#getOrganizationPaymentsOverview": [ID],
  "venue-payments#getStripeDashboardLink": [{ organizationId: ID }],
  "venue-payments#refreshStripeAccountStatus": [{ organizationId: ID }],
  "venue-payments#startStripeOnboarding": [{ organizationId: ID }],
  "venue-relationships#getPublicVenueRelationships": [ID],
  "venue-relationships#getTeamVenueRelationships": [ID_LIST],
  "venue-relationships#getVenueRelationshipAdminData": [ID, ID],
  "venue-relationships#getVenueRelationshipInvitation": [ID],
  "venue-relationships#inviteVenueRelationship": [{ organizationId: ID, venueId: ID, teamId: ID, leagueId: ID }],
  "venue-relationships#removeVenueRelationship": [{ organizationId: ID, venueId: ID, relationshipId: ID }],
  "venue-relationships#respondToVenueRelationship": [{ relationshipId: ID }],
  "venue-requests#annotateIceTimeRequest": [{ organizationId: ID, venueId: ID, requestId: ID }],
  "venue-requests#cancelIceTimeRequest": [{ organizationId: ID, venueId: ID, requestId: ID }],
  "venue-requests#decideIceTimeRequest": [{ organizationId: ID, venueId: ID, requestId: ID, approvedSurfaceId: ID, approvedSegmentId: ID }],
  "venue-requests#expireIceTimeRequest": [{ organizationId: ID, venueId: ID, requestId: ID }],
  "venue-requests#getVenueRequestQueue": [ID, ID],
  "venue-requests#submitIceTimeRequest": [{ scheduleBlockId: ID, venueId: ID, requesterTeamId: ID, requesterLeagueId: ID }],
  "venue-reservations#assignVenueReservation": [{ reservationId: ID, targetId: ID }],
  "venue-reservations#cancelVenueReservation": [{ reservationId: ID }],
  "venue-reservations#checkVenueReservationAvailability": [{ venueId: ID, surfaceId: ID, segmentId: ID, excludeReservationId: ID }],
  "venue-reservations#completeVenueReservation": [{ reservationId: ID }],
  "venue-reservations#markVenueReservationUnused": [{ reservationId: ID }],
  "venue-reservations#releaseVenueReservation": [{ reservationId: ID }],
  "venue-reservations#rescheduleVenueReservation": [{ reservationId: ID }],
  "venue-reservations#unassignVenueReservation": [{ reservationId: ID, targetId: ID }],
  "venue-schedules#archiveIceSurface": [{ organizationId: ID, venueId: ID, surfaceId: ID }],
  "venue-schedules#cancelScheduleBlock": [{ organizationId: ID, venueId: ID, scheduleBlockId: ID }],
  "venue-schedules#createIceSurface": [{ organizationId: ID, venueId: ID }],
  "venue-schedules#createScheduleBlock": [{ organizationId: ID, venueId: ID, surfaceId: ID, segmentId: ID }],
  "venue-schedules#deleteOperatingHours": [{ organizationId: ID, venueId: ID, operatingHourId: ID }],
  "venue-schedules#getPublicVenueSchedule": [SLUG, { skillLevelIds: ID_LIST }],
  "venue-schedules#getVenueScheduleAdminData": [ID, ID],
  "venue-schedules#getVenueScheduleBoard": [{ organizationId: ID, venueId: ID }],
  "venue-schedules#publishScheduleBlock": [{ organizationId: ID, venueId: ID, scheduleBlockId: ID }],
  "venue-schedules#setOperatingHours": [{ organizationId: ID, venueId: ID, surfaceId: ID }],
  "venue-schedules#updateIceSurface": [{ organizationId: ID, venueId: ID, surfaceId: ID }],
  "venue-schedules#updateOperatingHours": [{ organizationId: ID, venueId: ID, surfaceId: ID, operatingHourId: ID }],
  "venue-schedules#updateScheduleBlock": [{ organizationId: ID, venueId: ID, surfaceId: ID, scheduleBlockId: ID, segmentId: ID }],
  "venue-staff#acceptVenueStaffInvite": [ID],
  "venue-staff#declineVenueStaffInvite": [ID],
  "venue-staff#inviteVenueStaff": [{ organizationId: ID }],
  "venue-staff#removeStaff": [{ organizationId: ID, staffId: ID }],
  "venue-staff#updateStaffRole": [{ organizationId: ID, staffId: ID }],
  "venue-surfaces#applySegmentationPreset": [{ surfaceId: ID }],
  "venue-surfaces#createSegment": [{ surfaceId: ID }],
  "venue-surfaces#getSurfaceSegmentation": [{ surfaceId: ID }],
  "venue-surfaces#setSegmentActive": [{ segmentId: ID }],
  "venue-surfaces#setWholeSurfaceLabel": [{ surfaceId: ID }],
  "venue-surfaces#suggestCoexistence": [{ surfaceId: ID, excludeSegmentId: ID }],
  "venue-surfaces#updateSegment": [{ segmentId: ID }],
  "venues#checkVenueAvailability": [{ venueId: ID, excludeEventId: ID }],
  "venues#createVenue": [{ teamId: ID, leagueId: ID, organizationId: ID }],
  "venues#deleteVenue": [ID],
  "venues#getVenue": [ID],
  "venues#getVenuePageData": [ID],
  "venues#updateVenue": [{ id: ID, teamId: ID, leagueId: ID, organizationId: ID }],
  "volunteers#assignVolunteer": [{ needId: ID, userId: ID }],
  "volunteers#cancelVolunteerNeed": [ID],
  "volunteers#completeVolunteerAssignment": [ID],
  "volunteers#createVolunteerNeed": [{ leagueId: ID, divisionId: ID, teamId: ID, eventId: ID, signupEventId: ID }],
  "volunteers#getVolunteerBoard": [ID],
  "volunteers#markVolunteerAssignmentMissed": [ID],
  "volunteers#respondToVolunteerAssignment": [{ assignmentId: ID }],
  "volunteers#updateVolunteerNeed": [{ needId: ID }],
};

/** Exports that take no identifier argument, with the reason. */
export const NO_ID_ARGUMENTS: Record<string, string> = {
  "account#changePassword": "passwords only; the user comes from the session",
  "account#deleteAccount": "password only; the user comes from the session",
  "account#requestEmailChange": "email and password only; the user comes from the session",
  "account#updateProfile": "profile fields only; the user comes from the session",
  "account-lifecycle#requestPasswordReset": "takes an email address only",
  "account-lifecycle#resendVerificationEmail": "takes an email address only",
  "admin#getAllUsers": "no arguments",
  "admin#getPendingApprovals": "no arguments",
  "event-registrations#getMyEventRegistrations": "no arguments",
  "guardians#getMyPlayers": "no arguments",
  "league#createLeague": "league fields only; creates a new record",
  "logout#logout": "no arguments",
  "notifications#getAllNotificationPreferences": "no arguments",
  "practice-session-queries#getPlanImportTeams": "no arguments",
  "practice-session-queries#getPlayLibraryContext": "no arguments",
  "practice-session-queries#getPracticePlannerListData": "no arguments",
  "session-registrations#getMyRegistrations": "no arguments",
  "signup-events#listMyHostOptions": "no arguments",
  "signup-events#listMySignupEvents": "no arguments",
  "signup-events#listMySignupEventsGrouped": "no arguments",
  "signup-events#listVenueOptions": "no arguments",
  "team#createTeam": "team fields only; creates a new record",
  "team-context#getCalendarData": "takes a date window only; teams come from the session",
  "team-context#getRosterData": "no arguments",
  "team-context#getUserAdminTeamContext": "no arguments",
  "team-context#getUserTeamContext": "no arguments",
  "venue-content#getSkillLevelReferences": "no arguments",
  "venue-organizations#createVenueOrganization": "organization fields only; creates a new record",
  "venue-organizations#getPublicRinkSummaries": "no arguments",
  "venue-organizations#getVenueAdminDashboard": "no arguments",
  "venue-staff#getMyPendingVenueStaffInvites": "no arguments",
  "venues#getAvailableVenues": "takes text and enum filters only; visibility comes from the session",
  "venues#getVenueFormContext": "no arguments",
  "venues#getVenuesPageAccess": "no arguments",
};
