import {
  HEX_TOKEN,
  ID,
  ID_LIST,
  SHARE_TOKEN,
  SLUG,
  variants,
  type TableEntry,
} from "@/__tests__/helpers/action-id-sweep";
import { serializePlan } from "@/lib/plan-document";
import { createEmptyPlayData } from "@/lib/utils/play-data";

/** A minimal valid practice plan document for the import action. */
const SAMPLE_PLAN = serializePlan(
  {
    title: "Sweep Practice",
    durationMinutes: 10,
    date: "2026-11-01",
    startTime: "18:00",
    drills: [
      {
        sequence: 0,
        duration: 10,
        runsWithPrevious: false,
        instructions: null,
        name: "Laps",
        description: null,
        playData: createEmptyPlayData(),
      },
    ],
  },
  "openleague-static",
  new Date("2026-10-01T00:00:00.000Z"),
);

/**
 * Every export of every "use server" module under lib/actions, keyed
 * "<module>#<export>". Each entry is an argument template for one call (or
 * `variants(...)` when ids are mutually exclusive): the markers (ID, ID_LIST,
 * SLUG, HEX_TOKEN, SHARE_TOKEN) are the identifier positions the sweep test
 * fills with malformed values, one position at a time, while every other
 * marker gets a well-formed value. Every other field holds a valid value, so
 * with well-formed markers the call passes input validation; the sweep checks
 * this, so a malformed-value case cannot pass merely because a required field
 * was missing.
 *
 * A new server action must be added here (or to NO_ID_ARGUMENTS) or the
 * guard test fails.
 */
export const ACTION_ID_ARGUMENTS: Record<string, TableEntry> = {
  "account-lifecycle#confirmEmailChange": [SHARE_TOKEN],
  "account-lifecycle#confirmEmailVerification": [SHARE_TOKEN],
  "account-lifecycle#resetPassword": [{ token: SHARE_TOKEN, password: "a-strong-password-1" }],
  "admin#approveUser": [ID],
  "admin#rejectUser": [ID],
  "association-profile#getPublicAssociationProfile": [SLUG],
  "association-profile#getPublicAssociationTeams": [ID],
  "association-profile#getPublicTeamProfile": [ID, SLUG],
  "association-profile#resolveActiveAssociation": [SLUG],
  "association-profile#resolvePublicAssociation": [SLUG],
  "association-profile#resolvePublicTeam": [ID, SLUG],
  "association-profile#setAssociationProfilePublished": [{ leagueId: ID, publish: false }],
  "association-profile#updateAssociationProfile": [{ leagueId: ID }],
  "association-profile#updateAssociationSlug": [{ leagueId: ID, slug: SLUG }],
  "association-profile#updateTeamPublicProfile": [{ leagueId: ID, teamId: ID, slug: SLUG }],
  "association-roles#grantAssociationResponsibility": [{ leagueId: ID, userId: ID, divisionId: ID, teamId: ID, seasonId: ID, eventId: ID, signupEventId: ID, role: "ASSOCIATION_ADMIN", scopeType: "ASSOCIATION" }],
  "association-roles#inviteAssociationOperator": [{ leagueId: ID, teamId: ID, divisionId: ID, seasonId: ID, eventId: ID, signupEventId: ID, role: "ASSOCIATION_ADMIN", scopeType: "ASSOCIATION", email: "sweep@example.com" }],
  "association-roles#listAssociationResponsibilityGrants": [ID],
  "association-roles#revokeAssociationResponsibility": [{ grantId: ID, leagueId: ID }],
  "audit#getAuditActionsForLeague": [ID],
  "audit#getAuditLogsAction": [{ leagueId: ID }],
  "auth#signup": [{ invitationToken: HEX_TOKEN, email: "sweep@example.com", password: "a-strong-password-1" }],
  "branding#clearEntityLogo": [{ entityId: ID, entity: "team" }],
  "branding#setEntityBrandColors": [{ entityId: ID, entity: "team" }],
  "branding#setEntityLogo": [{ entityId: ID, entity: "team", url: "https://example.com/a.png" }],
  "communication#getLeagueMessages": [{ leagueId: ID }],
  "communication#getTeamMessages": [{ teamId: ID }],
  "communication#sendLeagueMessage": [{ leagueId: ID, targeting: { divisionIds: ID_LIST, teamIds: ID_LIST }, subject: "Sample", content: "Sample" }],
  "communication#sendTeamMessage": [{ teamId: ID, subject: "Sample", content: "Sample" }],
  "event-invitations#listEventInvitations": [ID],
  "event-invitations#resendEventInvitation": [{ invitationId: ID }],
  "event-invitations#revokeEventInvitation": [{ invitationId: ID }],
  "event-invitations#sendEventInvitations": [{ eventId: ID, emails: ["sweep@example.com"] }],
  "event-managers#addEventManager": [{ eventId: ID, email: "sweep@example.com" }],
  "event-managers#listEventManagers": [ID],
  "event-managers#removeEventManager": [{ managerId: ID }],
  "event-media#finalizeEventMediaUpload": [{ eventId: ID, url: "https://example.com/a.png", contentType: "Sample", sizeBytes: 1 }],
  "event-media#listEventMedia": [{ eventId: ID, linkToken: HEX_TOKEN }],
  "event-media#removeEventMediaItem": [{ mediaItemId: ID }],
  "event-media#reportEventMediaItem": [{ mediaItemId: ID }],
  "event-registrations#cancelMyEventRegistration": [{ registrationId: ID }],
  "event-registrations#claimWaitlistOffer": [{ registrationId: ID }],
  "event-registrations#declineWaitlistOffer": [{ registrationId: ID }],
  "event-registrations#getEventRoster": [{ eventId: ID }],
  "event-registrations#promoteWaitlistEntry": [{ registrationId: ID }],
  "event-registrations#refundEventRegistration": [{ registrationId: ID }],
  "event-registrations#registerForSignupEvent": [{ eventId: ID, slotId: ID, linkToken: HEX_TOKEN, participants: [{ name: "Sample" }] }],
  "event-registrations#removeEventRegistration": [{ registrationId: ID }],
  "event-registrations#setEventCheckIn": [{ registrationId: ID, checkedIn: false }],
  "event-registrations#setManualPaymentStatus": [{ registrationId: ID, status: "UNPAID" }],
  "event-teams#assignToEventTeam": [{ eventTeamId: ID, registrationIds: ID_LIST }],
  "event-teams#deleteEventGame": [{ gameId: ID }],
  "event-teams#deleteEventTeam": [{ teamId: ID }],
  "event-teams#getEventStandings": [ID, HEX_TOKEN],
  "event-teams#getEventTeamsBoard": [ID],
  "event-teams#getMyEventAssignments": [ID],
  "event-teams#getPublicEventGames": [ID, HEX_TOKEN],
  "event-teams#listPublicVenueEventGames": [ID],
  "event-teams#publishEventTeams": [{ eventId: ID }],
  "event-teams#recordGameResult": [{ gameId: ID, homeScore: 1, awayScore: 1 }],
  "event-teams#removeTeamAssignment": [{ registrationId: ID }],
  "event-teams#setFloater": [{ registrationId: ID, isFloater: false }],
  "event-teams#setGameRotation": [{ gameId: ID, entries: [] }],
  "event-teams#upsertEventGame": [{ eventId: ID, homeTeamId: ID, awayTeamId: ID, gameId: ID, surfaceId: ID, segmentId: ID, reservationId: ID, venueId: ID, startAt: "2026-11-01T18:00:00.000Z", endAt: "2026-11-01T19:00:00.000Z" }],
  "event-teams#upsertEventTeam": [{ eventId: ID, teamId: ID, name: "Sample" }],
  "events#createEvent": [{ teamId: ID, venueId: ID, reservationId: ID, title: "Sample", location: "Sample", type: "PRACTICE", startAt: "2026-11-01T18:00:00.000Z", endAt: "2026-11-01T19:00:00.000Z" }],
  "events#createInterTeamGame": [{ leagueId: ID, homeTeamId: ID, awayTeamId: ID, title: "Sample", location: "Sample", startAt: "2026-11-01T18:00:00.000Z" }],
  "events#deleteEvent": [ID],
  "events#getEvent": [ID],
  "events#getTeamEvents": [ID],
  "events#updateEvent": [{ teamId: ID, id: ID, venueId: ID, reservationId: ID, title: "Sample", location: "Sample", type: "PRACTICE", startAt: "2026-11-01T18:00:00.000Z", endAt: "2026-11-01T19:00:00.000Z" }],
  "game-proposals#acceptGameProposal": [{ proposalId: ID, reservationId: ID }],
  "game-proposals#counterGameProposal": [{ proposalId: ID, venueId: ID, startAt: "2026-11-01T18:00:00.000Z", endAt: "2026-11-01T19:00:00.000Z" }],
  "game-proposals#createGameProposal": [{ proposingTeamId: ID, receivingTeamId: ID, seasonId: ID, venueId: ID, startAt: "2026-11-01T18:00:00.000Z", endAt: "2026-11-01T19:00:00.000Z" }],
  "game-proposals#declineGameProposal": [{ proposalId: ID }],
  "game-proposals#getProposalsForLeague": [ID],
  "game-proposals#getProposalsForTeam": [ID],
  "game-proposals#withdrawGameProposal": [{ proposalId: ID }],
  "gear-context#getGearInventoryContext": [ID],
  "gear-context#getGearReservationContext": [ID],
  "gear-inventory#adjustGearPoolStock": [{ leagueId: ID, catalogItemId: ID, locationId: ID, condition: "NEW", quantityDelta: 1, expectedVersion: 0 }],
  "gear-inventory#archiveGearCatalogItem": [{ leagueId: ID, catalogItemId: ID }],
  "gear-inventory#archiveGearStorageLocation": [{ leagueId: ID, locationId: ID }],
  "gear-inventory#changeGearUnitCondition": [{ leagueId: ID, unitId: ID, condition: "NEW", expectedVersion: 0 }],
  "gear-inventory#createGearCatalogItem": [{ leagueId: ID, name: "Sample", category: "Sample", trackingMode: "POOLED" }],
  "gear-inventory#createGearStorageLocation": [{ leagueId: ID, name: "Sample" }],
  "gear-inventory#createGearUnit": [{ leagueId: ID, catalogItemId: ID, currentLocationId: ID }],
  "gear-inventory#retireGearUnit": [{ leagueId: ID, unitId: ID, expectedVersion: 0, notes: "Sample" }],
  "gear-inventory#transferGearPoolStock": [{ leagueId: ID, catalogItemId: ID, sourceLocationId: ID, destinationLocationId: ID, condition: "NEW", quantity: 1, expectedSourceVersion: 0 }],
  "gear-inventory#transferGearUnit": [{ leagueId: ID, unitId: ID, destinationLocationId: ID, expectedVersion: 0 }],
  "gear-inventory#unretireGearUnit": [{ leagueId: ID, unitId: ID, destinationLocationId: ID, expectedVersion: 0, condition: "NEW", notes: "Sample" }],
  "gear-inventory#updateGearCatalogItem": [{ leagueId: ID, catalogItemId: ID, name: "Sample" }],
  "gear-inventory#updateGearStorageLocation": [{ leagueId: ID, locationId: ID, name: "Sample" }],
  "gear-inventory#updateGearUnit": [{ leagueId: ID, unitId: ID, expectedVersion: 0, notes: "Sample" }],
  "gear-needs#approveTeamGearNeed": [{ leagueId: ID, needId: ID, expectedVersion: 0 }],
  "gear-needs#cancelTeamGearNeed": [{ leagueId: ID, needId: ID, expectedVersion: 0 }],
  "gear-needs#createTeamGearNeed": [{ leagueId: ID, teamId: ID, idempotencyKey: "Samplexxxxxxxxxx", title: "Sample", lines: [{ nameSnapshot: "Sample", requestedQty: 1 }] }],
  "gear-needs#decideTeamGearNeed": [{ leagueId: ID, needId: ID, expectedVersion: 0, status: "APPROVED" }],
  "gear-needs#fulfillTeamGearNeed": [{ leagueId: ID, needId: ID, expectedVersion: 0 }],
  "gear-needs#getGearNeedDetail": [ID, ID],
  "gear-needs#getGearNeedsContext": [ID],
  "gear-needs#getTeamGearNeeds": [ID, ID],
  "gear-needs#submitTeamGearNeed": [{ leagueId: ID, needId: ID, expectedVersion: 0 }],
  "gear-pledges#cancelGearPledge": [{ leagueId: ID, pledgeId: ID, expectedVersion: 0 }],
  "gear-pledges#correctGearPledgeReceipt": [{ leagueId: ID, pledgeId: ID, receiptId: ID, expectedVersion: 0, reason: "Sample" }],
  "gear-pledges#createGearPledge": [{ wishlistToken: SHARE_TOKEN, wishlistItemId: ID, donorName: "Sample", quantity: 1, idempotencyKey: "Samplexxxxxxxxxx", donorEmail: "sweep@example.com", contactConsent: true }],
  "gear-pledges#createPublicGearPledge": [{ wishlistToken: SHARE_TOKEN, wishlistItemId: ID, donorName: "Sample", quantity: 1, idempotencyKey: "Samplexxxxxxxxxx", donorEmail: "sweep@example.com", contactConsent: true }],
  "gear-pledges#declineGearPledge": [{ leagueId: ID, pledgeId: ID, expectedVersion: 0 }],
  "gear-pledges#expireGearPledge": [{ leagueId: ID, pledgeId: ID, expectedVersion: 0 }],
  "gear-pledges#getGearPledgeAdminContext": [ID],
  "gear-pledges#getGearPledgesForAdmin": [ID],
  "gear-pledges#receiveGearPledge": [{ leagueId: ID, pledgeId: ID, catalogItemId: ID, poolStockId: ID, locationId: ID, expectedVersion: 0, idempotencyKey: "Samplexxxxxxxxxx", quantity: 1 }],
  "gear-pledges#redactGearPledgePii": [{ leagueId: ID, pledgeId: ID, expectedVersion: 0 }],
  "gear-pledges#updateGearPledgeStatus": [{ leagueId: ID, pledgeId: ID, expectedVersion: 0, status: "DECLINED" }],
  "gear-reservations#approveAndAllocateGearReservation": variants(
    [{ leagueId: ID, reservationId: ID, expectedVersion: 0, allocations: [{ reservationLineId: ID, poolStockId: ID, quantity: 1 }] }],
    [{ leagueId: ID, reservationId: ID, expectedVersion: 0, allocations: [{ reservationLineId: ID, gearUnitId: ID, quantity: 1 }] }],
  ),
  "gear-reservations#cancelGearReservation": [{ leagueId: ID, reservationId: ID, expectedVersion: 0 }],
  "gear-reservations#createGearReservation": [{ leagueId: ID, teamId: ID, requestedStartDate: "2026-11-01", requestedEndDate: "2026-11-02", custodianNameSnapshot: "Sample", lines: [{ nameSnapshot: "Sample", requestedQty: 1 }] }],
  "gear-reservations#declineGearReservation": [{ leagueId: ID, reservationId: ID, expectedVersion: 0 }],
  "gear-reservations#getGearReservationAllocationOptions": [{ leagueId: ID, reservationId: ID, reservationLineId: ID, expectedVersion: 0, approvedStartDate: "2026-11-01", approvedEndDate: "2026-11-02" }],
  "gear-reservations#recordGearPickup": [{ leagueId: ID, allocationId: ID, expectedVersion: 0, quantity: 1 }],
  "gear-reservations#recordGearReturn": [{ leagueId: ID, allocationId: ID, expectedVersion: 0, quantity: 1, returnDisposition: "GOOD" }],
  "gear-reservations#releaseGearAllocation": [{ leagueId: ID, allocationId: ID, expectedVersion: 0 }],
  "gear-reservations#rescheduleGearReservation": [{ leagueId: ID, reservationId: ID, expectedVersion: 0, requestedStartDate: "2026-11-01", requestedEndDate: "2026-11-02" }],
  "gear-wishlist#archiveGearWishlist": [{ leagueId: ID, expectedVersion: 0 }],
  "gear-wishlist#getGearWishlistAdminContext": [ID],
  "gear-wishlist#getGearWishlistForAdmin": [ID],
  "gear-wishlist#getPublicGearWishlist": [SHARE_TOKEN],
  "gear-wishlist#rotateGearWishlistShareToken": [{ leagueId: ID, expectedVersion: 0 }],
  "gear-wishlist#saveGearWishlist": [{ leagueId: ID, title: "Sample", publish: false, items: [] }],
  "gear-wishlist#setGearWishlistStatus": [{ leagueId: ID, expectedVersion: 0, status: "PUBLISHED" }],
  "guardians#addGuardian": [{ playerId: ID, email: "sweep@example.com" }],
  "guardians#listGuardians": [ID],
  "guardians#removeGuardian": [{ guardianId: ID }],
  "invitations#resendInvitation": [ID],
  "invitations#sendInvitation": [{ teamId: ID, email: "sweep@example.com" }],
  "invitations#sendLeagueInvitation": [{ teamId: ID, leagueId: ID, email: "sweep@example.com" }],
  "invitations#sendLeagueMemberInvitation": [{ leagueId: ID, email: "sweep@example.com" }],
  "league#addTeamToLeague": [{ leagueId: ID, divisionId: ID, name: "Sample", season: "Sample", sport: "HOCKEY" }],
  "league#assignTeamToDivision": [{ teamId: ID, divisionId: ID, leagueId: ID }],
  "league#createDivision": [{ leagueId: ID, name: "Sample" }],
  "league#deleteDivision": [{ id: ID, leagueId: ID }],
  "league#exportAttendanceReportCSV": [ID],
  "league#exportAttendanceReportPDF": [ID],
  "league#exportFinancialReportCSV": [ID],
  "league#exportFinancialReportPDF": [ID],
  "league#exportLeagueRosterCSV": [ID],
  "league#exportLeagueRosterPDF": [ID],
  "league#exportLeagueScheduleCSV": [ID],
  "league#exportLeagueSchedulePDF": [ID],
  "league#getLeagueDivisions": [ID],
  "league#getLeagueStatisticsData": [ID],
  "league#getLeagueTeamsPaginated": [{ leagueId: ID, divisionId: ID }],
  "league#getLeagueTeamsWithDivisions": [ID],
  "league#getLeagueWithStats": [ID],
  "league#migrateTeamToLeague": [{ teamId: ID, leagueData: { name: "Sample", contactEmail: "sweep@example.com", sport: "HOCKEY" } }],
  "league#updateDivision": [{ id: ID, leagueId: ID, name: "Sample" }],
  "league#updateLeagueSettings": [{ id: ID, name: "Sample", contactEmail: "sweep@example.com", sport: "HOCKEY" }],
  "league-context#getLeagueInvitationsData": [ID],
  "league-context#getLeagueMessagesData": [ID],
  "league-context#getLeagueRosterData": [ID],
  "league-context#getLeagueScheduleData": [ID],
  "league-context#getNewLeagueGameContext": [ID],
  "league-payments#getLeaguePaymentsOverview": [ID],
  "league-payments#getLeagueStripeDashboardLink": [{ leagueId: ID }],
  "league-payments#refreshLeagueStripeStatus": [{ leagueId: ID }],
  "league-payments#startLeagueStripeOnboarding": [{ leagueId: ID }],
  "notifications#generateUnsubscribeToken": [ID],
  "notifications#getNotificationPreferences": [ID],
  "notifications#handleUnsubscribe": [{ token: HEX_TOKEN }],
  "notifications#updateNotificationPreferences": [{ leagueId: ID, preferences: {} }],
  "permissions#assignLeagueRoleAction": [{ leagueId: ID, targetUserId: ID, role: "LEAGUE_ADMIN" }],
  "permissions#assignTeamRoleAction": [{ leagueId: ID, teamId: ID, targetUserId: ID, role: "ADMIN" }],
  "permissions#checkPermissionAction": [ID, undefined, ID],
  "permissions#getLeagueUsersAction": [{ leagueId: ID }],
  "permissions#getTeamMembersWithRoles": [ID, ID],
  "permissions#getUserPermissionsAction": [{ leagueId: ID, targetUserId: ID }],
  "permissions#removeLeagueRoleAction": [{ leagueId: ID, targetUserId: ID }],
  "permissions#removeTeamRoleAction": [{ leagueId: ID, teamId: ID, targetUserId: ID }],
  "placements#createDivisionInline": [{ leagueId: ID, name: "Sample" }],
  "placements#getPlacementBoard": [{ seasonId: ID, phaseId: ID }],
  "placements#recordPlacement": [{ seasonId: ID, teamId: ID, divisionId: ID }],
  "plays#createPlay": [{ teamId: ID, name: "Sample", playData: { version: 2, players: [], drawings: [], equipment: [], annotations: [] } }],
  "plays#deletePlay": [{ id: ID, teamId: ID }],
  "plays#getPlayById": [{ id: ID, teamId: ID }],
  "plays#getPlaysByTeam": [{ teamId: ID }],
  "plays#updatePlay": [{ id: ID, teamId: ID, name: "Sample", playData: { version: 2, players: [], drawings: [], equipment: [], annotations: [] } }],
  "practice-logo#getPracticeLogoImage": [ID],
  "practice-plan-import#importPracticePlan": [{ teamId: ID, date: "2026-11-01T18:00:00.000Z", document: SAMPLE_PLAN }],
  "practice-session-drills#copySessionDrillToLibrary": [{ playId: ID, teamId: ID }],
  "practice-session-drills#duplicatePracticeSession": [{ id: ID, teamId: ID, date: "2026-11-01T18:00:00.000Z" }],
  "practice-session-drills#saveSessionDrill": [{ sessionId: ID, teamId: ID, playId: ID, name: "Sample", playData: { version: 2, players: [], drawings: [], equipment: [], annotations: [] } }],
  "practice-session-queries#getPracticeSessionDetail": [ID],
  "practice-session-queries#getPracticeSessionForEdit": [ID],
  "practice-session-queries#getPracticeStaffOptions": [ID],
  "practice-sessions#createPracticeSession": [{ teamId: ID, venueId: ID, surfaceId: ID, segmentId: ID, reservationId: ID, title: "Sample", duration: 1, date: "2026-11-01T18:00:00.000Z", startAt: "2026-11-01T18:00:00.000Z" }],
  "practice-sessions#deletePracticeSession": [{ id: ID, teamId: ID }],
  "practice-sessions#getPracticeSessionById": [{ id: ID, teamId: ID }],
  "practice-sessions#getPracticeSessionsByTeam": [{ teamId: ID }],
  "practice-sessions#sharePracticeSession": [{ id: ID, teamId: ID, isShared: false }],
  "practice-sessions#updatePracticeSession": [{ id: ID, teamId: ID, venueId: ID, surfaceId: ID, segmentId: ID, reservationId: ID, title: "Sample", duration: 1, date: "2026-11-01T18:00:00.000Z", startAt: "2026-11-01T18:00:00.000Z" }],
  "public-content#archivePublicContent": [ID],
  "public-content#createPublicContent": [{ leagueId: ID, slug: SLUG, teamId: ID, title: "Sample", body: "Sample" }],
  "public-content#getPublicContentItem": [SLUG, SLUG],
  "public-content#listAssociationContent": [ID],
  "public-content#listPublicAssociationContent": [ID],
  "public-content#listPublicAssociationContentPage": [ID],
  "public-content#updatePublicContent": [{ itemId: ID }],
  "roster#addPlayer": [{ teamId: ID, name: "Sample" }],
  "roster#deletePlayer": [ID, ID],
  "roster#exportLeagueRoster": [ID],
  "roster#transferPlayer": [{ playerId: ID, fromTeamId: ID, toTeamId: ID, leagueId: ID }],
  "roster#updatePlayer": [{ teamId: ID, id: ID, name: "Sample" }],
  "roster#updateTeamMemberUsahId": [{ teamMemberId: ID, teamId: ID }],
  "rsvp#getEventAttendance": [ID],
  "rsvp#submitRSVP": [{ eventId: ID, playerId: ID, status: "GOING" }],
  "rsvp#updateRSVP": [{ eventId: ID, playerId: ID, status: "GOING" }],
  "season-games#cancelSeasonGame": [{ gameId: ID }],
  "season-games#checkGameConflicts": [{ venueId: ID, surfaceId: ID, excludeGameId: ID, startAt: "2026-11-01T18:00:00.000Z", endAt: "2026-11-01T19:00:00.000Z" }],
  "season-games#createSeasonGame": [{ homeTeamId: ID, awayTeamId: ID, seasonId: ID, phaseId: ID, venueId: ID, surfaceId: ID, segmentId: ID, reservationId: ID, startAt: "2026-11-01T18:00:00.000Z", endAt: "2026-11-01T19:00:00.000Z" }],
  "season-games#deleteDraftGame": [{ gameId: ID }],
  "season-games#publishSeasonGames": [{ seasonId: ID, gameIds: ID_LIST }],
  "season-games#recordSeasonGameScore": [{ gameId: ID, homeScore: 1, awayScore: 1 }],
  "season-games#updateSeasonGame": [{ gameId: ID, phaseId: ID, venueId: ID, surfaceId: ID, segmentId: ID, reservationId: ID }],
  "season-generation#generateRoundRobin": [{ seasonId: ID, teamIds: [ID, ID], phaseId: ID, defaultVenueId: ID, eligibleDays: [1], startTime: "18:00", startDate: "2026-11-01T18:00:00.000Z", endDate: "2026-11-01T19:00:00.000Z" }],
  "season-generation#previewRoundRobin": [{ seasonId: ID, teamIds: [ID, ID], phaseId: ID, defaultVenueId: ID, eligibleDays: [1], startTime: "18:00", startDate: "2026-11-01T18:00:00.000Z", endDate: "2026-11-01T19:00:00.000Z" }],
  "seasons#archiveSeason": [{ seasonId: ID }],
  "seasons#createSeason": variants(
    [{ leagueId: ID, name: "Sample", startDate: "2026-11-01T18:00:00.000Z", endDate: "2026-11-01T19:00:00.000Z" }],
    [{ teamId: ID, name: "Sample", startDate: "2026-11-01T18:00:00.000Z", endDate: "2026-11-01T19:00:00.000Z" }],
  ),
  "seasons#createSeasonPhase": [{ seasonId: ID, name: "Sample", startDate: "2026-11-01T18:00:00.000Z", endDate: "2026-11-01T19:00:00.000Z" }],
  "seasons#deleteSeasonPhase": [{ phaseId: ID }],
  "seasons#getSeasonDetail": [ID],
  "seasons#getSeasons": [{ leagueId: ID, teamId: ID }],
  "seasons#unarchiveSeason": [{ seasonId: ID }],
  "seasons#updateSeason": [{ seasonId: ID }],
  "seasons#updateSeasonPhase": [{ phaseId: ID }],
  "session-registrations#cancelMyRegistration": [{ registrationId: ID }],
  "session-registrations#getVenueRegistrations": [{ organizationId: ID, venueId: ID }],
  "session-registrations#refundRegistration": [{ organizationId: ID, venueId: ID, registrationId: ID }],
  "session-registrations#registerForSession": variants(
    [{ venueId: ID, scheduleBlockId: ID, participantName: "Sample", participantEmail: "sweep@example.com", quantity: 1 }],
    [{ venueId: ID, lessonOfferingId: ID, participantName: "Sample", participantEmail: "sweep@example.com", quantity: 1 }],
  ),
  "signup-events#cancelSignupEvent": [{ eventId: ID }],
  "signup-events#createSignupEvent": variants(
    [{ venueId: ID, hostOrganizationId: ID, title: "Sample", slots: [{ name: "Sample" }], startAt: "2026-11-01T18:00:00.000Z", endAt: "2026-11-01T19:00:00.000Z" }],
    [{ venueId: ID, hostLeagueId: ID, title: "Sample", slots: [{ name: "Sample" }], startAt: "2026-11-01T18:00:00.000Z", endAt: "2026-11-01T19:00:00.000Z" }],
    [{ venueId: ID, hostTeamId: ID, title: "Sample", slots: [{ name: "Sample" }], startAt: "2026-11-01T18:00:00.000Z", endAt: "2026-11-01T19:00:00.000Z" }],
  ),
  "signup-events#duplicateSignupEvent": [{ eventId: ID }],
  "signup-events#getManagedSignupEvent": [ID],
  "signup-events#getPublicSignupEvent": [{ eventId: ID, linkToken: HEX_TOKEN }],
  "signup-events#listHostGroupOptions": [{ kind: "league", id: ID, eventId: ID }],
  "signup-events#listPublicSignupEvents": [{ venueId: ID, hostLeagueId: ID, hostOrganizationId: ID }],
  "signup-events#publishSignupEvent": [{ eventId: ID }],
  "signup-events#regenerateEventLink": [{ eventId: ID }],
  "signup-events#updateSignupEvent": [{ eventId: ID, venueId: ID, title: "Sample", slots: [{ name: "Sample" }], startAt: "2026-11-01T18:00:00.000Z", endAt: "2026-11-01T19:00:00.000Z" }],
  "team#updateTeam": [{ id: ID, name: "Sample", season: "Sample", sport: "HOCKEY" }],
  "team-context#getTeamOverviewData": [ID],
  "team-context#getTeamRosterDataById": [ID],
  "team-officials#createTeamOfficial": [{ teamId: ID, name: "Sample", role: "HEAD_COACH" }],
  "team-officials#getTeamOfficials": [ID],
  "team-officials#inviteTeamOfficial": [{ teamId: ID, email: "sweep@example.com", name: "Sample", role: "HEAD_COACH" }],
  "team-officials#removeTeamOfficial": [{ teamId: ID, officialId: ID }],
  "team-officials#updateTeamOfficial": [{ teamId: ID, officialId: ID, name: "Sample", role: "HEAD_COACH" }],
  "venue-content#archiveLessonOffering": [{ organizationId: ID, venueId: ID, lessonOfferingId: ID }],
  "venue-content#archiveVenueContentPost": [{ organizationId: ID, venueId: ID, postId: ID }],
  "venue-content#assignSkillLevelsToLesson": [{ organizationId: ID, venueId: ID, skillLevelIds: ID_LIST, lessonOfferingId: ID, scheduleBlockId: ID }],
  "venue-content#assignSkillLevelsToScheduleBlock": [{ organizationId: ID, venueId: ID, skillLevelIds: ID_LIST, scheduleBlockId: ID, lessonOfferingId: ID }],
  "venue-content#createLessonOffering": [{ organizationId: ID, venueId: ID, surfaceId: ID, title: "Sample", lessonType: "PRIVATE" }],
  "venue-content#createSkillLevelReference": [{ organizationId: ID, venueId: ID, source: "USA_HOCKEY", discipline: "HOCKEY", label: "Sample" }],
  "venue-content#getPublicVenueContent": [ID, { skillLevelIds: ID_LIST }],
  "venue-content#getVenueContentAdminData": [ID, ID],
  "venue-content#publishLessonOffering": [{ organizationId: ID, venueId: ID, lessonOfferingId: ID }],
  "venue-content#publishSpecialtyEvent": [{ organizationId: ID, venueId: ID, surfaceId: ID, segmentId: ID, title: "Sample", startsAt: "2026-11-01T18:00:00.000Z", endsAt: "2026-11-01T19:00:00.000Z", activityType: "OPEN_SKATE" }],
  "venue-content#saveVenueContentPost": [{ organizationId: ID, venueId: ID, slug: SLUG, postId: ID, title: "Sample", body: "Sample" }],
  "venue-layout#clearVenueLayout": [ID],
  "venue-layout#getVenueLayout": [ID],
  "venue-layout#saveVenueLayout": [{ venueId: ID, layout: { surfaces: [], labels: [] } }],
  "venue-organizations#attachVenueToOrganization": [{ organizationId: ID, venueId: ID }],
  "venue-organizations#createOrganizationVenue": [{ teamId: ID, leagueId: ID, organizationId: ID, name: "Sample" }],
  "venue-organizations#getPublicRinkProfile": [SLUG],
  "venue-organizations#publishVenueProfile": [{ organizationId: ID, venueId: ID }],
  "venue-organizations#updateVenueProfile": [{ organizationId: ID, venueId: ID, slug: SLUG }],
  "venue-payments#getOrganizationPaymentsOverview": [ID],
  "venue-payments#getStripeDashboardLink": [{ organizationId: ID }],
  "venue-payments#refreshStripeAccountStatus": [{ organizationId: ID }],
  "venue-payments#startStripeOnboarding": [{ organizationId: ID }],
  "venue-relationships#getPublicVenueRelationships": [ID],
  "venue-relationships#getTeamVenueRelationships": [ID_LIST],
  "venue-relationships#getVenueRelationshipAdminData": [ID, ID],
  "venue-relationships#getVenueRelationshipInvitation": [ID],
  "venue-relationships#inviteVenueRelationship": [{ organizationId: ID, venueId: ID, teamId: ID, leagueId: ID, relationshipType: "PREFERRED", targetType: "TEAM" }],
  "venue-relationships#removeVenueRelationship": [{ organizationId: ID, venueId: ID, relationshipId: ID }],
  "venue-relationships#respondToVenueRelationship": [{ relationshipId: ID, response: "ACCEPT" }],
  "venue-requests#annotateIceTimeRequest": [{ organizationId: ID, venueId: ID, requestId: ID, decisionMessage: "Sample" }],
  "venue-requests#cancelIceTimeRequest": [{ organizationId: ID, venueId: ID, requestId: ID }],
  "venue-requests#decideIceTimeRequest": [{ organizationId: ID, venueId: ID, requestId: ID, approvedSurfaceId: ID, approvedSegmentId: ID, status: "UNDER_REVIEW" }],
  "venue-requests#expireIceTimeRequest": [{ organizationId: ID, venueId: ID, requestId: ID }],
  "venue-requests#getVenueRequestQueue": [ID, ID],
  "venue-requests#submitIceTimeRequest": [{ scheduleBlockId: ID, venueId: ID, requesterTeamId: ID, requesterLeagueId: ID, contactName: "Sample", contactEmail: "sweep@example.com", requestedStartAt: "2026-11-01T18:00:00.000Z", requestedEndAt: "2026-11-01T19:00:00.000Z" }],
  "venue-reservations#assignVenueReservation": [{ reservationId: ID, targetId: ID, targetType: "SEASON_GAME" }],
  "venue-reservations#cancelVenueReservation": [{ reservationId: ID, reason: "Sample" }],
  "venue-reservations#checkVenueReservationAvailability": [{ venueId: ID, surfaceId: ID, segmentId: ID, excludeReservationId: ID, startsAt: "2026-11-01T18:00:00.000Z", endsAt: "2026-11-01T19:00:00.000Z", mode: "PUBLIC" }],
  "venue-reservations#completeVenueReservation": [{ reservationId: ID, reason: "Sample" }],
  "venue-reservations#markVenueReservationUnused": [{ reservationId: ID, reason: "Sample" }],
  "venue-reservations#releaseVenueReservation": [{ reservationId: ID, reason: "Sample" }],
  "venue-reservations#rescheduleVenueReservation": [{ reservationId: ID, startsAt: "2026-11-01T18:00:00.000Z", endsAt: "2026-11-01T19:00:00.000Z", reason: "Sample" }],
  "venue-reservations#unassignVenueReservation": [{ reservationId: ID, targetId: ID, targetType: "SEASON_GAME", reason: "Sample" }],
  "venue-schedules#archiveIceSurface": [{ organizationId: ID, venueId: ID, surfaceId: ID }],
  "venue-schedules#cancelScheduleBlock": [{ organizationId: ID, venueId: ID, scheduleBlockId: ID }],
  "venue-schedules#createIceSurface": [{ organizationId: ID, venueId: ID, name: "Sample" }],
  "venue-schedules#createScheduleBlock": [{ organizationId: ID, venueId: ID, surfaceId: ID, segmentId: ID, title: "Sample", activityType: "OPEN_SKATE", startsAt: "2026-11-01T18:00:00.000Z", endsAt: "2026-11-01T19:00:00.000Z" }],
  "venue-schedules#deleteOperatingHours": [{ organizationId: ID, venueId: ID, operatingHourId: ID }],
  "venue-schedules#getPublicVenueSchedule": [SLUG, { skillLevelIds: ID_LIST }],
  "venue-schedules#getVenueScheduleAdminData": [ID, ID],
  "venue-schedules#getVenueScheduleBoard": [{ organizationId: ID, venueId: ID, from: "2026-11-01T18:00:00.000Z", to: "2026-11-01T19:00:00.000Z" }],
  "venue-schedules#publishScheduleBlock": [{ organizationId: ID, venueId: ID, scheduleBlockId: ID }],
  "venue-schedules#setOperatingHours": [{ organizationId: ID, venueId: ID, surfaceId: ID, dayOfWeek: 1, opensAt: "06:00", closesAt: "22:00", effectiveStartDate: "2026-11-01" }],
  "venue-schedules#updateIceSurface": [{ organizationId: ID, venueId: ID, surfaceId: ID, name: "Sample" }],
  "venue-schedules#updateOperatingHours": [{ organizationId: ID, venueId: ID, surfaceId: ID, operatingHourId: ID, dayOfWeek: 1, opensAt: "06:00", closesAt: "22:00", effectiveStartDate: "2026-11-01" }],
  "venue-schedules#updateScheduleBlock": [{ organizationId: ID, venueId: ID, surfaceId: ID, scheduleBlockId: ID, segmentId: ID, title: "Sample", activityType: "OPEN_SKATE", startsAt: "2026-11-01T18:00:00.000Z", endsAt: "2026-11-01T19:00:00.000Z" }],
  "venue-staff#acceptVenueStaffInvite": [ID],
  "venue-staff#declineVenueStaffInvite": [ID],
  "venue-staff#inviteVenueStaff": [{ organizationId: ID, email: "sweep@example.com", role: "OWNER" }],
  "venue-staff#removeStaff": [{ organizationId: ID, staffId: ID }],
  "venue-staff#updateStaffRole": [{ organizationId: ID, staffId: ID, role: "OWNER" }],
  "venue-surfaces#applySegmentationPreset": [{ surfaceId: ID }],
  "venue-surfaces#createSegment": [{ surfaceId: ID, name: "Sample", geometry: { x: 1, y: 1, w: 1, h: 1, rotation: 1 } }],
  "venue-surfaces#getSurfaceSegmentation": [{ surfaceId: ID }],
  "venue-surfaces#setSegmentActive": [{ segmentId: ID, isActive: false }],
  "venue-surfaces#setWholeSurfaceLabel": [{ surfaceId: ID }],
  "venue-surfaces#suggestCoexistence": [{ surfaceId: ID, excludeSegmentId: ID, geometry: { x: 1, y: 1, w: 1, h: 1, rotation: 1 } }],
  "venue-surfaces#updateSegment": [{ segmentId: ID }],
  "venues#checkVenueAvailability": [{ venueId: ID, excludeEventId: ID, startAt: "2026-11-01T18:00:00.000Z", endAt: "2026-11-01T19:00:00.000Z" }],
  "venues#createVenue": [{ teamId: ID, leagueId: ID, organizationId: ID, name: "Sample" }],
  "venues#deleteVenue": [ID],
  "venues#getVenue": [ID],
  "venues#getVenuePageData": [ID],
  "venues#updateVenue": [{ id: ID, teamId: ID, leagueId: ID, organizationId: ID, name: "Sample" }],
  "volunteers#assignVolunteer": [{ needId: ID, userId: ID }],
  "volunteers#cancelVolunteerNeed": [ID],
  "volunteers#completeVolunteerAssignment": [ID],
  "volunteers#createVolunteerNeed": [{ leagueId: ID, divisionId: ID, teamId: ID, eventId: ID, signupEventId: ID, roleLabel: "Sample", capacity: 1, startAt: "2026-11-01T18:00:00.000Z", endAt: "2026-11-01T19:00:00.000Z", timezone: "America/Chicago" }],
  "volunteers#getVolunteerBoard": [ID],
  "volunteers#markVolunteerAssignmentMissed": [ID],
  "volunteers#respondToVolunteerAssignment": [{ assignmentId: ID, response: "ACCEPTED" }],
  "volunteers#updateVolunteerNeed": [{ needId: ID }],
};

/** Exports that take no identifier argument, with the reason. */
export const NO_ID_ARGUMENTS: Record<string, string> = {
  "account#changePassword": "passwords only; the user comes from the session",
  "account#deleteAccount": "password only; the user comes from the session",
  "account#requestEmailChange": "email and password only; the user comes from the session",
  "account#updateProfile": "profile fields only; the user comes from the session",
  "account-lifecycle#requestPasswordReset": "takes an email address only",
  "account-lifecycle#resendVerificationEmail": "takes an email address only",
  "admin#getAllUsers": "no arguments",
  "admin#getPendingApprovals": "no arguments",
  "event-registrations#getMyEventRegistrations": "no arguments",
  "guardians#getMyPlayers": "no arguments",
  "league#createLeague": "league fields only; creates a new record",
  "logout#logout": "no arguments",
  "notifications#getAllNotificationPreferences": "no arguments",
  "practice-session-queries#getPlanImportTeams": "no arguments",
  "practice-session-queries#getPlayLibraryContext": "no arguments",
  "practice-session-queries#getPracticePlannerListData": "no arguments",
  "session-registrations#getMyRegistrations": "no arguments",
  "signup-events#listMyHostOptions": "no arguments",
  "signup-events#listMySignupEvents": "no arguments",
  "signup-events#listMySignupEventsGrouped": "no arguments",
  "signup-events#listVenueOptions": "no arguments",
  "team#createTeam": "team fields only; creates a new record",
  "team-context#getCalendarData": "takes a date window only; teams come from the session",
  "team-context#getRosterData": "no arguments",
  "team-context#getUserAdminTeamContext": "no arguments",
  "team-context#getUserTeamContext": "no arguments",
  "venue-content#getSkillLevelReferences": "no arguments",
  "venue-organizations#createVenueOrganization": "organization fields only; creates a new record",
  "venue-organizations#getPublicRinkSummaries": "no arguments",
  "venue-organizations#getVenueAdminDashboard": "no arguments",
  "venue-staff#getMyPendingVenueStaffInvites": "no arguments",
  "venues#getAvailableVenues": "takes text and enum filters only; visibility comes from the session",
  "venues#getVenueFormContext": "no arguments",
  "venues#getVenuesPageAccess": "no arguments",
};

/**
 * Table entries whose well-formed call legitimately uses none of the template
 * values in a query or authorization helper, with the reason.
 */
export const VALID_TEMPLATE_EXEMPTIONS: Record<string, string> = {
  "admin#approveUser": "the system-admin check refuses the sweep user before the id is used; the id is schema-checked",
  "admin#rejectUser": "the system-admin check refuses the sweep user before the id is used; the id is schema-checked",
  "practice-session-queries#getPracticeSessionDetail":
    "returns early for a user with no team membership, before the session id is used; the id is parsed first",
};
